# https://www.emqx.io/docs/zh/v4.4/getting-started/config.html
# https://docs.emqx.com/zh/enterprise/v4.4/getting-started/config.html
# https://www.emqx.io/docs/zh/v4.4/configuration/configuration.html
# https://www.emqx.io/docs/zh/v4.4/tutorial/tune.html
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: emqx
immutable: false
data:
  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/etc/emqx.conf
  emqx.conf: |
    listener.tcp.external = 0.0.0.0:1883
    listener.ssl.external = 0.0.0.0:8883
    listener.ssl.external.keyfile =
    listener.ssl.external.certfile =
    listener.ssl.external.cacertfile =
    listener.ssl.external.verify = verify_peer
    listener.ssl.external.fail_if_no_peer_cert = true
    listener.ssl.external.peer_cert_as_username = cn
    listener.ssl.external.peer_cert_as_clientid = cn
    listener.ws.external = 8083
    listener.ws.external.mqtt_path = /mqtt
    listener.ws.external.peer_cert_as_username = cn
    listener.ws.external.peer_cert_as_clientid = cn
    listener.ws.external.compress = true
    listener.wss.external = 8084
    listener.wss.external.mqtt_path = /mqtt
    listener.wss.external.verify = verify_peer
    listener.wss.external.fail_if_no_peer_cert = true
    listener.wss.external.peer_cert_as_username = cn
    listener.wss.external.peer_cert_as_clientid = cn
    listener.wss.external.keyfile =
    listener.wss.external.certfile =
    listener.wss.external.cacertfile =

    allow_anonymous = false
    acl_file =
    acl_nomatch = deny
    acl_deny_action = disconnect
    enable_acl_cache = on
    acl_cache_ttl = 1m

    # https://www.emqx.io/docs/zh/v4.4/getting-started/cluster.html
    # https://www.emqx.io/docs/zh/v4.4/advanced/cluster.html
    cluster.name = mqtt-cloud
    # cluster.discovery = k8s
    # cluster.k8s.apiserver = https://kube-apiserver.kube-system.svc.cluster.local:{{kube.apiserver.port}}
    # cluster.k8s.app_name = emqx
    # cluster.k8s.address_type = hostname
    # cluster.k8s.service_name = emqx-headless
    # cluster.k8s.namespace = aiot-case
    # cluster.k8s.suffix = svc.cluster.local
    cluster.autoheal = on
    cluster.autoclean = 5m
    cluster.proto_dist = inet_tls

    node.name =
    node.cookie = mqtt-cloud
    node.data_dir =
    node.ssl_dist_optfile =
    node.process_limit = 2097152
    node.max_ports = 1048576

    rpc.enable_ssl = 5369
    rpc.driver = ssl
    rpc.default_client_driver = ssl
    rpc.keyfile =
    rpc.certfile =
    rpc.cacertfile =

    # https://www.emqx.io/docs/zh/v4.4/getting-started/log.html
    log.to = console
    log.formatter = text
    log.level = info

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/etc/ssl_dist.conf
  ssl-dist.conf: |

    [
      {
        server,
        [
          { keyfile, "etc/certs/tls.key" },
          { certfile, "etc/certs/tls.crt" },
          { cacertfile, "etc/certs/ca.crt" },
          { secure_renegotiate, true },
          { depth, 0 }
        ]
      },
      {
        client,
        [
          { keyfile, "etc/certs/tls.key" },
          { certfile, "etc/certs/tls.crt" },
          { cacertfile, "etc/certs/ca.crt" },
          { secure_renegotiate, true }
        ]
      }
    ].


  # authentication: https://www.emqx.io/docs/zh/v4.4/advanced/auth.html
  # authorization: https://www.emqx.io/docs/zh/v4.4/advanced/acl.html

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_auth_mnesia/etc/emqx_auth_mnesia.conf
  # https://www.emqx.io/docs/zh/v4.4/advanced/auth-mnesia.html
  auth-mnesia.conf: |
    auth.mnesia.password_hash = sha256

    auth.user.1.username = edge-app
    auth.user.1.password = edge-app
    auth.user.2.username = mqtt-edge
    auth.user.2.password = mqtt-edge
    auth.user.3.username = mqttx
    auth.user.3.password = mqttx

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_auth_jwt/etc/emqx_auth_jwt.conf
  # https://www.emqx.io/docs/zh/v4.4/advanced/auth-jwt.html
  auth-jwt.conf: |

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/etc/acl.conf
  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/deploy/charts/emqx/templates/configmap.acl.yaml
  # https://www.emqx.io/docs/zh/v4.4/advanced/acl-file.html
  acl.conf: |


  # retain message
  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_retainer/etc/emqx_retainer.conf
  # https://www.emqx.io/docs/zh/v4.4/advanced/retained.html
  retainer.conf: |
    retainer.storage_type = disc_only
    retainer.max_payload_size = 256KB
    retainer.max_retained_messages = 0
    retainer.expiry_interval = 16m
    retainer.stop_publish_clear_msg = false

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_bridge_mqtt/etc/emqx_bridge_mqtt.conf
  # https://www.emqx.io/docs/zh/v4.4/advanced/bridge.html
  # https://www.emqx.io/docs/zh/v4.4/bridge/bridge.html
  # https://www.emqx.io/docs/zh/v4.4/bridge/bridge-mqtt.html
  bridge-mqtt.conf: |

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_web_hook/etc/emqx_web_hook.conf
  # https://www.emqx.io/docs/zh/v4.4/advanced/webhook.html
  webhook.conf: |

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_rule_engine/etc/emqx_rule_engine.conf
  rule-engine.conf: |


  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_management/etc/emqx_management.conf
  api.conf: |
    management.application.default_secret = mqtt-cloud
    management.default_application.id = mqtt-cloud
    management.default_application.secret = mqtt-cloud

    # management.listener.http = 8081
    # management.listener.http.max_clients = 512
    management.listener.https = 8081
    management.listener.https.max_clients = 512
    management.listener.https.keyfile =
    management.listener.https.certfile =
    management.listener.https.cacertfile =
    management.listener.https.verify = verify_peer
    management.listener.https.fail_if_no_peer_cert = true

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/lib-ce/emqx_dashboard/etc/emqx_dashboard.conf
  # https://www.emqx.io/docs/zh/v4.4/getting-started/dashboard.html
  dashboard.conf: |
    dashboard.listener.http.inet6 = false
    dashboard.listener.http.ipv6_v6only = false
    dashboard.listener.http = 18083
    dashboard.listener.http.acceptors = 8
    dashboard.listener.http.max_clients = 128
    dashboard.listener.https.inet6 = false
    dashboard.listener.https.ipv6_v6only = false
    dashboard.listener.https = 18084
    dashboard.listener.https.acceptors = 8
    dashboard.listener.https.max_clients = 128
    dashboard.listener.https.keyfile = etc/certs/tls.key
    dashboard.listener.https.certfile = etc/certs/tls.crt
    dashboard.listener.https.cacertfile = etc/certs/ca.crt
    dashboard.listener.https.verify = verify_none
    dashboard.listener.https.fail_if_no_peer_cert = false
    dashboard.listener.https.secure_renegotiate = on
    dashboard.listener.https.reuse_sessions = on

    # dashboard.default_user.login = mqtt-cloud
    # dashboard.default_user.password = mqtt-cloud


  # prometheus agent
  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_prometheus/etc/emqx_prometheus.conf
  # metric: https://www.emqx.io/docs/zh/v4.4/advanced/metrics-and-stats.html
  # topic metric: https://www.emqx.io/docs/zh/v4.4/advanced/topic-metrics.html
  # alert: https://www.emqx.io/docs/zh/v4.4/advanced/alarms.html
  # grafana: https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/apps/emqx_prometheus/grafana_template/
  prometheus.conf: |
    prometheus.push.gateway.server =


  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/data/loaded_modules.tmpl
  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/deploy/charts/emqx/templates/configmap.loadedModules.yaml
  # https://docs.emqx.com/zh/enterprise/v4.4/modules/modules.html
  loaded-modules: |

    # acl
    { emqx_mod_acl_internal, true }.
    # online and offline notification
    # https://docs.emqx.com/zh/enterprise/v4.4/modules/presence.html
    { emqx_mod_presence, true }.
    # topic rewrite
    # https://www.emqx.io/docs/zh/v4.4/advanced/topic-rewrite.html
    { emqx_mod_rewrite, false }.
    # delayed publish
    # https://www.emqx.io/docs/zh/v4.4/advanced/delay-publish.html
    { emqx_mod_delayed, false }.
    # mqtt subscription
    # https://www.emqx.io/docs/zh/v4.4/advanced/proxy-subscriptions.html
    { emqx_mod_subscription, true }.
    # slow subscriptions statistics
    # https://docs.emqx.com/zh/enterprise/v4.4/modules/slow_subscribers_statistics.html
    { emqx_mod_slow_subs, true }.
    # topic metric
    { emqx_mod_topic_metrics, true }.
    # trace
    # https://docs.emqx.com/zh/enterprise/v4.4/modules/tracer.html
    { emqx_mod_trace, true }.

  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/data/loaded_plugins.tmpl
  # https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/deploy/charts/emqx/templates/configmap.loadedPlugins.yaml
  # https://docs.emqx.com/zh/enterprise/v4.4/advanced/plugins.html
  loaded-plugins: |

    # authentication and authorization
    { emqx_auth_mnesia, true}.
    { emqx_auth_jwt, true}.
    { emqx_auth_pgsql, false}.
    { emqx_auth_mysql, false}.
    { emqx_auth_mongo, false}.
    { emqx_auth_redis, false}.
    { emqx_auth_ldap, false}.
    { emqx_auth_http, false}.

    # retain message
    { emqx_retainer, true }.
    # message bridge
    { emqx_bridge_mqtt, true }.
    # message persistence
    # https://docs.emqx.com/zh/enterprise/v4.4/backend/backend_pgsql.html
    # webhook
    { emqx_web_hook, true}.
    # rule engine based sql
    # https://www.emqx.io/docs/zh/v4.4/rule/bridge_mqtt.html
    # https://docs.emqx.com/zh/enterprise/v4.4/rule/backend_tdengine.html
    # https://docs.emqx.com/zh/enterprise/v4.4/rule/backend_pgsql.html
    # https://docs.emqx.com/zh/enterprise/v4.4/rule/offline_msg_to_pgsql.html
    { emqx_rule_engine, true }.

    # api
    { emqx_management, true }.
    # dashboard
    { emqx_dashboard, true }.

    # prometheus agent
    { emqx_prometheus, true }.
    # https://www.emqx.io/docs/zh/v4.4/advanced/telemetry.html
    { emqx_telemetry, false }.


    # performance debugging
    # https://docs.emqx.com/zh/enterprise/v4.4/modules/recon.html
    { emqx_recon, false }.

# https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/deploy/charts/emqx/templates/configmap.env.yaml
# https://www.emqx.io/docs/zh/v4.4/configuration/environment-variable.html
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: emqx-env
immutable: false
data:
  # erlang node.name: erlang unique identifier
  EMQX_NODE__NAME: emqx@${POD_NAME}.${SERVICE_NAME}.${POD_NAMESPACE}.svc.cluster.local

  EMQX_CLUSTER__DISCOVERY: k8s
  EMQX_CLUSTER__K8S__APISERVER: https://kube-apiserver.kube-system.svc.cluster.local:{{kube.apiserver.port}}
  EMQX_CLUSTER__K8S__APP_NAME: emqx
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: hostname
  EMQX_CLUSTER__K8S__SERVICE_NAME: emqx-headless
  EMQX_CLUSTER__K8S__NAMESPACE: aiot-case
  EMQX_CLUSTER__K8S__SUFFIX: svc.cluster.local
