# https://www.emqx.io/docs/zh/v4.4/tutorial/deploy.html

# https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/deploy/charts/emqx/templates/service.yaml
---
kind: Service
apiVersion: v1
metadata:
  namespace: &app-namespace aiot-case
  name: &app-name emqx
  labels: &app-label
    app.kubernetes.io/name: emqx
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: *app-namespace
    app.kubernetes.io/managed-by: kube
spec:
  selector:
    <<: *app-label
  publishNotReadyAddresses: false
  ports:
    # - name: tcp
    #   protocol: TCP
    #   port: 1883
    #   targetPort: 1883
    - name: tcp-tls
      protocol: TCP
      port: 8883
      targetPort: 8883
    # - name: websocket
    #   protocol: TCP
    #   port: 8083
    #   targetPort: 8083
    - name: websocket-tls
      protocol: TCP
      port: 8084
      targetPort: 8084
    # - name: api
    #   protocol: TCP
    #   port: 8080
    #   targetPort: 8080
    - name: api-https
      protocol: TCP
      port: 8081
      targetPort: 8081
    # - name: dashboard
    #   protocol: TCP
    #   port: 18083
    #   targetPort: 18083
    - name: dashboard-https
      protocol: TCP
      port: 18084
      targetPort: 18084
  type: NodePort
  sessionAffinity: None
---
kind: Service
apiVersion: v1
metadata:
  namespace: &app-namespace aiot-case
  name: &app-name emqx-headless
  labels: &app-label
    app.kubernetes.io/name: emqx
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: *app-namespace
    app.kubernetes.io/managed-by: kube
spec:
  selector:
    <<: *app-label
  publishNotReadyAddresses: true
  ports:
    # - name: tcp
    #   protocol: TCP
    #   port: 1883
    #   targetPort: 1883
    - name: tcp-tls
      protocol: TCP
      port: 8883
      targetPort: 8883
    # - name: websocket
    #   protocol: TCP
    #   port: 8083
    #   targetPort: 8083
    - name: websocket-tls
      protocol: TCP
      port: 8084
      targetPort: 8084
    - name: ekka
      protocol: TCP
      port: 4370
      targetPort: 4370
    - name: ekka-rpc
      protocol: TCP
      port: 5370
      targetPort: 5370
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None

# https://github.com/emqx/emqx/blob/v{{kubethings.aiot.cloud.emqx.app.version}}/deploy/charts/emqx/templates/StatefulSet.yaml
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: &app-namespace aiot-case
  name: &app-name emqx
  # annotations:
  #   kubereloader.kubestation.aiot.hk/auto: "true"
spec:
  serviceName: emqx-headless

  replicas: 3
  selector:
    matchLabels: &app-label
      app.kubernetes.io/name: emqx
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: *app-namespace
      app.kubernetes.io/managed-by: kube
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  revisionHistoryLimit: 5

  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data
      spec:
        storageClassName: {{kubestorage.remoteStorage.csi.ceph.rbd.storageClassName}}
        resources:
          requests:
            storage: 221Mi
          # limits:
          #   storage: 221Mi
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem

  template:
    metadata:
      labels:
        <<: *app-label

    spec:
      serviceAccountName: emqx

      terminationGracePeriodSeconds: 0
      nodeSelector:
        node-role.kubernetes.io/cloud: ""
        node-role.kubernetes.io/aiot-case: ""
      affinity:
        # nodeAffinity:
        #   preferredDuringSchedulingIgnoredDuringExecution:
        #     - weight: 100
        #       preference:
        #         matchExpressions:
        #           - key: node-role.kubernetes.io/aiot-case
        #             values:
        #               - ""
        #             operator: In
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    <<: *app-label
      tolerations:
        - operator: Exists

      hostIPC: false
      hostPID: false
      hostNetwork: false

      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: single-request-reopen

      restartPolicy: Always

      volumes:
        - name: config
          configMap:
            name: emqx
            items:
              - key: emqx.conf
                path: emqx.conf
              - key: ssl-dist.conf
                path: ssl-dist.conf

              - key: auth-mnesia.conf
                path: auth-mnesia.conf
              - key: auth-jwt.conf
                path: auth-jwt.conf
              - key: acl.conf
                path: acl.conf

              - key: retainer.conf
                path: retainer.conf
              - key: bridge-mqtt.conf
                path: bridge-mqtt.conf
              - key: webhook.conf
                path: webhook.conf
              - key: rule-engine.conf
                path: rule-engine.conf

              - key: api.conf
                path: api.conf
              - key: dashboard.conf
                path: dashboard.conf

              - key: prometheus.conf
                path: prometheus.conf

              - key: loaded-modules
                path: loaded-modules
              - key: loaded-plugins
                path: loaded-plugins
            defaultMode: 0644
            optional: true

        - name: cert
          secret:
            secretName: emqx-cert
            defaultMode: 0644
            optional: true

      containers:
        - image: {{kubethings.image.repository}}/emqx:{{kubethings.aiot.cloud.emqx.app.version}}
          imagePullPolicy: {{kubethings.image.pullPolicy}}
          name: *app-name

          volumeMounts:
            - name: config
              subPath: emqx.conf
              mountPath: /opt/emqx/etc/emqx.conf
              readOnly: false
            - name: config
              subPath: ssl-dist.conf
              mountPath: /opt/emqx/etc/ssl_dist.conf
              readOnly: false
            - name: cert
              mountPath: /opt/emqx/etc/pki/
              readOnly: true

            - name: config
              subPath: auth-mnesia.conf
              mountPath: /opt/emqx/etc/plugins/emqx_auth_mnesia.conf
              readOnly: false
            # - name: config
            #   subPath: auth-jwt.conf
            #   mountPath: /opt/emqx/etc/plugins/emqx_auth_jwt.conf
            #   readOnly: false
            # - name: config
            #   subPath: acl.conf
            #   mountPath: /opt/emqx/etc/acl.conf
            #   readOnly: false

            - name: config
              subPath: retainer.conf
              mountPath: /opt/emqx/etc/plugins/emqx_retainer.conf
              readOnly: false
            - name: config
              subPath: bridge-mqtt.conf
              mountPath: /opt/emqx/etc/plugins/emqx_bridge_mqtt.conf
              readOnly: false
            - name: config
              subPath: webhook.conf
              mountPath: /opt/emqx/etc/plugins/emqx_web_hook.conf
              readOnly: false
            - name: config
              subPath: rule-engine.conf
              mountPath: /opt/emqx/etc/plugins/emqx_rule_engine.conf
              readOnly: false

            - name: config
              subPath: api.conf
              mountPath: /opt/emqx/etc/plugins/emqx_management.conf
              readOnly: false
            - name: config
              subPath: dashboard.conf
              mountPath: /opt/emqx/etc/plugins/emqx_dashboard.conf
              readOnly: false

            - name: config
              subPath: prometheus.conf
              mountPath: /opt/emqx/etc/plugins/emqx_prometheus.conf
              readOnly: false

            - name: data
              mountPath: /opt/emqx/data
              readOnly: false
            - name: config
              subPath: loaded-modules
              mountPath: /opt/emqx/data/loaded_modules
              readOnly: false
            - name: config
              subPath: loaded-plugins
              mountPath: /opt/emqx/data/loaded_plugins
              readOnly: false

          envFrom:
            - configMapRef:
                name: emqx-env
                optional: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: EMQX_MANAGEMENT__APPLICATION__DEFAULT_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: EMQX_MANAGEMENT__DEFAULT_APPLICATION__ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: EMQX_DASHBOARD__DEFAULT_USER__LOGIN
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: EMQX_DASHBOARD__DEFAULT_USER__PASSWORD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          securityContext:
            runAsGroup: 0
            runAsUser: 0
            runAsNonRoot: false
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

          stdin: false
          tty: false
          terminationMessagePolicy: FallbackToLogsOnError
          terminationMessagePath: /dev/termination-log
          # lifecycle:
          #   preStop:
          #     exec:
          #       command:
          #         - /bin/bash
          #         - -c
          #         - |-
          #           /opt/emqx/bin/emqx-ctl cluster leave
          command:
            - /bin/bash
            - -c
            - |-
              if [[ ${EMQX_NODE__NAME} == "" ]]
              then
                  erlangNodeName="${EMQX_CLUSTER__K8S__APP_NAME}@${POD_NAME}.${EMQX_CLUSTER__K8S__SERVICE_NAME}.${EMQX_CLUSTER__K8S__NAMESPACE}.${EMQX_CLUSTER__K8S__SUFFIX}"

                  export EMQX_NODE__NAME=${erlangNodeName}

                  eval echo -e "export EMQX_NODE__NAME=${erlangNodeName}" >> /etc/profile.d/emqx.sh
                  echo -e 'source /etc/profile.d/emqx.sh' >> /root/.bashrc
              fi

              /opt/emqx/bin/emqx foreground

          ports:
            - name: tcp-internal
              protocol: TCP
              containerPort: &port-tcp-internal 11883
            - name: tcp
              protocol: TCP
              containerPort: &port-tcp 1883
            - name: tcp-tls
              protocol: TCP
              containerPort: &port-tcp-tls 8883
            - name: websocket
              protocol: TCP
              containerPort: &port-websocket 8083
            - name: websocket-tls
              protocol: TCP
              containerPort: &port-websocket-tls 8084
            - name: api
              protocol: TCP
              containerPort: &port-api 8080
            - name: api-https
              protocol: TCP
              containerPort: &port-api-https 8081
            - name: dashboard
              protocol: TCP
              containerPort: &port-dashboard 18083
            - name: dashboard-https
              protocol: TCP
              containerPort: &port-dashboard-https 18084
            - name: ekka
              protocol: TCP
              containerPort: &port-ekka 4370
            - name: ekka-rpc
              protocol: TCP
              containerPort: &port-ekka-rpc 5370
          startupProbe:
            httpGet:
              scheme: HTTP
              host: 127.0.0.1
              port: *port-api
              path: /status
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 24
          readinessProbe:
            httpGet:
              scheme: HTTP
              host: 127.0.0.1
              port: *port-api
              path: /status
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              scheme: HTTP
              host: 127.0.0.1
              port: *port-api
              path: /status
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
