# https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/deploy/docker/README.md#configuration
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: kuiper-env
immutable: false
data:
  # CONNECTION__MQTT__CLOUD__SERVER: ssl://emqx.${POD_NAMESPACE}.svc.cluster.local:8883
  # CONNECTION__MQTT__CLOUD__CLIENTID: kuiper_${NODE_NAME}_${NODE_IP}

# https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/deploy/chart/kuiper/templates/configmap.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: kuiper
immutable: false
data:
  # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/kuiper.yaml
  # https://ekuiper.org/docs/zh/latest/operation/config/configuration_file.html
  kuiper.yaml: |

    basic:
      # install source, function and sink plugin online
      pluginHosts: https://packages.emqx.net
      # sql
      ignoreCase: false

      # http api
      restIp: 0.0.0.0
      restPort: 9081
      restTls:
        cafile: /usr/local/kuiper/etc/pki/ca.crt
        keyfile: /usr/local/kuiper/etc/pki/tls.key
        certfile: /usr/local/kuiper/etc/pki/tls.crt
      # https://ekuiper.org/docs/zh/latest/operation/config/authentication.html
      authentication: false
      # cli
      ip: 0.0.0.0
      port: 20498

      # metric
      prometheus: true
      prometheusPort: 20499
      # log
      consoleLog: true
      fileLog: false
      rotateTime: 24
      maxAge: 72
      debug: false

    # https://ekuiper.org/docs/zh/latest/extension/overview.html
    # https://ekuiper.org/docs/zh/latest/extension/portable/overview.html
    portable:
      goBin: go
      pythonBin: python

    # https://ekuiper.org/docs/zh/latest/rules/overview.html
    # https://ekuiper.org/docs/zh/latest/rules/state_and_fault_tolerance.html
    rule:
      qos: 1
      checkpointInterval: 300000
      concurrency: 1
      bufferLength: 1024
      sendMetaToSink: true
      sendError: true
    sink:
      runAsync: false
      concurrency: 1
      bufferLength: 1024
      retryInterval: 2000
      retryCount: 3
      cacheThreshold: 10
      cacheTriggerCount: 15
      disableCache: true

    store:
      type: sqlite
      sqlite:
        name: sqliteKV.db
      redis:
        host: 127.0.0.1
        port: 6379
        password: kuiper
        timeout: 2000

  # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/client.yaml
  client.yaml: |

    basic:
      host: 127.0.0.1
      port: 20498


  # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/connections/connection.yaml
  connection.yaml: |

    mqtt:
      edge:
        server: tcp://127.0.0.1:1883
        protocolVersion: 5
        insecureSkipVerify: true
        rootCaPath: /usr/local/kuiper/etc/pki/mqtt-edge.ca.crt
        privateKeyPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.key
        certificationPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.crt
        username: kuiper
        password: kuiper
        clientid: kuiper
        qos: 1
        sharedSubscription: true
      cloud:
        # server: ssl://mqtt-cloud.${POD_NAMESPACE}.svc.cluster.local:8883
        protocolVersion: 5
        insecureSkipVerify: true
        rootCaPath: /usr/local/kuiper/etc/pki/mqtt-cloud.ca.crt
        privateKeyPath: /usr/local/kuiper/etc/pki/mqtt-cloud.client.tls.key
        certificationPath: /usr/local/kuiper/etc/pki/mqtt-cloud.client.tls.crt
        username: kuiper
        password: kuiper
        # clientid: kuiper_${NODE_NAME}_${NODE_IP}
        qos: 1
        sharedSubscription: true

    # edgex:
    #   redis:
    #     type: redis
    #     protocol: redis
    #     server: 127.0.0.1
    #     port: 6379
    #   mqtt:
    #     type: mqtt
    #     protocol: tcp
    #     server: 127.0.0.1
    #     port: 1883
    #     optional:
    #       SkipCertVerify: true
    #       CaFile: /usr/local/kuiper/etc/pki/mqtt-edge.ca.crt
    #       KeyFile: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.key
    #       CertFile: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.crt
    #       Username: kuiper
    #       Password: kuiper
    #       ClientId: kuiper
    #       Qos: 1
    #       sharedSubscription: true
    #   zeromq:
    #     type: zero
    #     protocol: tcp
    #     server: 127.0.0.1
    #     port: 5571

  # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/mqtt_source.yaml
  # https://ekuiper.org/docs/zh/latest/rules/sources/builtin/mqtt.html
  mqtt.yaml: |

    default:
      connectionSelector: mqtt.edge
      # server: tcp://127.0.0.1:1883
      # protocolVersion: 5
      # insecureSkipVerify: true
      # rootCaPath: /usr/local/kuiper/etc/pki/mqtt-edge.ca.crt
      # privateKeyPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.key
      # certificationPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.crt
      # username: kuiper
      # password: kuiper
      # clientid: kuiper
      # qos: 1
      # sharedSubscription: true
    edge:
      connectionSelector: mqtt.edge
    cloud:
      connectionSelector: mqtt.cloud

  # # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/sources/zmq.yaml
  # # https://ekuiper.org/docs/zh/latest/rules/sources/plugin/zmq.html
  # zeromq.yaml: |

  #   default:
  #     server: tcp://127.0.0.1:5563

  # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/sources/neuron.yaml
  # https://ekuiper.org/docs/zh/latest/rules/sources/builtin/neuron.html
  neuron.yaml: |

  # # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/sources/edgex.yaml
  # # https://ekuiper.org/docs/zh/latest/rules/sources/builtin/edgex.html
  # # https://ekuiper.org/docs/zh/latest/edgex/edgex_rule_engine_tutorial.html
  # # https://ekuiper.org/docs/zh/latest/edgex/edgex_source_tutorial.html
  # edgex.yaml: |

  #   default:
  #     connectionSelector: edgex.redis
  #     topic: events
  #     messageType: request
  #   redis:
  #     connectionSelector: edgex.redis
  #     topic: events
  #     messageType: request
  #   mqtt:
  #     connectionSelector: edgex.mqtt
  #     topic: events
  #     messageType: request
  #   zmq:
  #     connectionSelector: edgex.zeromq
  #     topic: events
  #     messageType: request

  # # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/sources/httppull.yaml
  # # https://ekuiper.org/docs/zh/latest/rules/sources/builtin/http_pull.html
  # http-get.yaml: |

  # # https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/etc/sources/random.yaml
  # # https://ekuiper.org/docs/zh/latest/rules/sources/plugin/random.html
  # random.yaml: |

---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: kuiper-manager
immutable: false
data:
  conf.yaml: |

    basic:
      host: 0.0.0.0
      port: 9082
      tls:
        cafile: /usr/local/kuiper-manager/pki/ca.crt
        keyfile: /usr/local/kuiper-manager/pki/tls.key
        certfile: /usr/local/kuiper-manager/pki/tls.crt

    jwt:
      secret: kuiper-manager
      expiration: 15
      refreshSecret: kuiper-manager
      refreshExpiration: 24

    accountLock:
      countRangeMinutes: 5
      maximumFailAttempts: 10
      durationMinutes: 10

    logger:
      debug: false
      consoleLog: true
      fileLog: false
