---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: kuiper-env
immutable: false
data:

# https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/deploy/chart/kuiper/templates/configmap.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: kuiper
immutable: false
data:
  # https://ekuiper.org/docs/zh/latest/operation/config/configuration_file.html
  kuiper.yaml: |

    basic:
      # source and function(named sink in kuiper) plugin
      pluginHosts: https://packages.emqx.net
      # sql
      ignoreCase: false

      # http api
      restIp: 0.0.0.0
      restPort: 9081
      restTls:
        cafile: /usr/local/kuiper/etc/pki/ca.crt
        keyfile: /usr/local/kuiper/etc/pki/tls.key
        certfile: /usr/local/kuiper/etc/pki/tls.crt
      # https://ekuiper.org/docs/zh/latest/operation/config/authentication.html
      authentication: false
      # cli
      ip: 0.0.0.0
      port: 20498

      # metric
      prometheus: true
      prometheusPort: 20499
      # log
      consoleLog: true
      fileLog: false
      rotateTime: 24
      maxAge: 72
      debug: false

    # https://ekuiper.org/docs/zh/latest/extension/portable/overview.html
    portable:
      pythonBin: python

    # https://ekuiper.org/docs/zh/latest/rules/overview.html
    rule:
      # https://ekuiper.org/docs/zh/latest/rules/state_and_fault_tolerance.html
      qos: 0
      checkpointInterval: 300000
      sendError: true
    sink:
      disableCache: true
      cacheThreshold: 10
      cacheTriggerCount: 15

    store:
      type: sqlite
      sqlite:
        name: sqliteKV.db
      redis:
        host: 127.0.0.1
        port: 6379
        password: kuiper
        timeout: 2000

  client.yaml: |

    basic:
      host: 127.0.0.1
      port: 20498


  connection.yaml: |

    mqtt:
      edge:
        server: tcp://127.0.0.1:1883
        protocolVersion: 5
        insecureSkipVerify: true
        rootCaPath: /usr/local/kuiper/etc/pki/mqtt-edge.ca.crt
        privateKeyPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.key
        certificationPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.crt
        username: kuiper
        password: kuiper
        clientid: kuiper
        qos: 1
      cloud:
        # server: tcp://mqtt-cloud.${POD_NAMESPACE}.svc.cluster.local:8883
        protocolVersion: 5
        insecureSkipVerify: true
        rootCaPath: /usr/local/kuiper/etc/pki/mqtt-cloud.ca.crt
        privateKeyPath: /usr/local/kuiper/etc/pki/mqtt-cloud.client.tls.key
        certificationPath: /usr/local/kuiper/etc/pki/mqtt-cloud.client.tls.crt
        username: kuiper
        password: kuiper
        # clientid: ${POD_NAMESPACE}_${NODE_NAME}_${NODE_IP}
        qos: 1

    edgex:
      mqtt:
        type: mqtt
        protocol: tcp
        server: 127.0.0.1
        port: 1883
        optional:
          SkipCertVerify: true
          CaFile: /usr/local/kuiper/etc/pki/mqtt-edge.ca.crt
          KeyFile: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.key
          CertFile: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.crt
          Username: kuiper
          Password: kuiper
          ClientId: kuiper
          Qos: 1
      zeromq:
        type: zero
        protocol: tcp
        server: 127.0.0.1
        port: 5571
      redis:
        type: redis
        protocol: redis
        server: 127.0.0.1
        port: 6379

  # https://ekuiper.org/docs/zh/latest/rules/sources/builtin/mqtt.html
  mqtt.yaml: |

    default:
      # connectionSelector: mqtt.edge
      server: tcp://127.0.0.1:1883
      protocolVersion: 5
      insecureSkipVerify: true
      rootCaPath: /usr/local/kuiper/etc/pki/mqtt-edge.ca.crt
      privateKeyPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.key
      certificationPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.crt
      username: kuiper
      password: kuiper
      clientid: kuiper
      qos: 1

  # https://ekuiper.org/docs/zh/latest/rules/sources/plugin/zmq.html
  zeromq.yaml: |

    default:
      server: tcp://127.0.0.1:5563

  # https://ekuiper.org/docs/zh/latest/rules/sources/builtin/edgex.html
  edgex.yaml: |

    default:
      connectionSelector: edgex.mqtt
      topic: events
      messageType: event
    mqtt_conf:
      connectionSelector: edgex.mqtt
      topic: events
      messageType: event
    zmq_conf:
      connectionSelector: edgex.zeromq
      topic: events
      messageType: event
    application_conf:
      connectionSelector: edgex.zeromq
      topic: application
      messageType: request
    share_conf:
      connectionSelector: edgex.redis
      topic: events
      messageType: event

  # https://ekuiper.org/docs/zh/latest/rules/sources/plugin/random.html
  random.yaml: |

    default:
      pattern:
        count: 50
      seed: 1
      deduplicate: 0
      interval: 1000
