---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: kuiper-env
immutable: false
data:

# https://github.com/lf-edge/ekuiper/blob/{{kubethings.aiot.edge.kuiper.version}}/deploy/chart/kuiper/templates/configmap.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: aiot-case
  name: kuiper
immutable: false
data:
  # https://ekuiper.org/docs/zh/latest/operation/config/configuration_file.html
  kuiper.yaml: |

    basic:
      # source and function(named sink in kuiper) plugin
      pluginHosts: https://packages.emqx.net
      # sql
      ignoreCase: false

      # http api
      restIp: 0.0.0.0
      restPort: 9081
      restTls:
        keyfile: /usr/local/kuiper/etc/pki/tls.key
        certfile: /usr/local/kuiper/etc/pki/tls.crt
        cafile: /usr/local/kuiper/etc/pki/ca.crt
      # https://ekuiper.org/docs/zh/latest/operation/config/authentication.html
      authentication: false
      # cli
      ip: 0.0.0.0
      port: 20498

      # metric
      prometheus: true
      prometheusPort: 20499
      # log
      fileLog: false
      rotateTime: 24
      maxAge: 72
      consoleLog: true
      debug: false

    # https://ekuiper.org/docs/zh/latest/extension/portable/overview.html
    portable:
      pythonBin: python

    # https://ekuiper.org/docs/zh/latest/rules/overview.html
    rule:
      # https://ekuiper.org/docs/zh/latest/rules/state_and_fault_tolerance.html
      qos: 0
      checkpointInterval: 300000
      sendError: true
    sink:
      disableCache: true
      cacheThreshold: 10
      cacheTriggerCount: 15

    store:
      type: sqlite
      sqlite:
        name: sqliteKV.db
      redis:
        host: 127.0.0.1
        port: 6379
        password: kuiper
        timeout: 2000

  client.yaml: |

    basic:
      host: 127.0.0.1
      port: 20498


  # https://ekuiper.org/docs/zh/latest/rules/sources/builtin/mqtt.html
  mqtt_source.yaml: |

    default:
      server: tcp://127.0.0.1:1883
      privateKeyPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.key
      certificationPath: /usr/local/kuiper/etc/pki/mqtt-edge.client.tls.crt
      rootCaPath: /usr/local/kuiper/etc/pki/mqtt-edge.ca.crt
      insecureSkipVerify: true
      username:
      password:
      protocolVersion: 5
      clientid: kuiper
      qos: 1

  # https://ekuiper.org/docs/zh/latest/rules/sources/plugin/zmq.html
  zmq.yaml: |

    default:
      server: tcp://127.0.0.1:5563

  # https://ekuiper.org/docs/zh/latest/rules/sources/builtin/edgex.html
  edgex.yaml: |

    application_conf:
      messageType: request
      port: 5571
      protocol: tcp
      server: localhost
      topic: application
      type: zero
    default:
      messageType: event
      port: 5563
      protocol: redis
      server: localhost
      topic: events
      type: redis
    mqtt_conf:
      optional:
        ClientId: client1
      port: 1883
      protocol: tcp
      server: 127.0.0.1
      topic: events
      type: mqtt
    share_conf:
      connectionSelector: edgex.redisMsgBus
      port: 1883
      protocol: tcp
      server: 127.0.0.1
      topic: events
      type: mqtt
    zmq_conf:
      messageType: event
      port: 5563
      protocol: tcp
      server: localhost
      topic: events
      type: zero

  # https://ekuiper.org/docs/zh/latest/rules/sources/plugin/random.html
  random.yaml: |

    default:
      pattern:
        count: 50
      seed: 1
      deduplicate: 0
      interval: 1000
