---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{kubethings.namespace}}
  name: emqx-operator-env
immutable: false
data:
  KUBERNETES_SERVICE_HOST: kube-apiserver.kube-system.svc.cluster.local
  KUBERNETES_SERVICE_PORT: "{{kube.apiserver.port}}"

# https://github.com/emqx/emqx-operator/blob/{{kubethings.aiot.cloud.emqx.operator.version}}/deploy/manifests/emqx-operator-controller.yaml
# https://github.com/emqx/emqx-operator/blob/{{kubethings.aiot.cloud.emqx.operator.version}}/config/manager/controller_manager_config.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{kubethings.namespace}}
  name: emqx-operator
immutable: false
data:
  config.yaml: |-

    kind: ControllerManagerConfig
    apiVersion: controller-runtime.sigs.k8s.io/v1beta1
    webhook:
      host: 0.0.0.0
      port: 9443
      certDir: /etc/emqx-operator/pki/
    leaderElection:
      leaderElect: true
      resourceName: 19fd6fcc.emqx.io
    health:
      healthProbeBindAddress: 0.0.0.0:8081
      readinessEndpointName: readyz
      livenessEndpointName: healthz
    metrics:
      bindAddress: 0.0.0.0:8080
