# https://github.com/emqx/emqx-operator/blob/1.1.6/deploy/manifests/emqx-operator-controller.yaml

---
kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: emqx-operator-self-signed
spec:
  selfSigned:
    crlDistributionPoints:
      - "https://aiot.hk"
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  namespace: &app-namespace kube-extension
  name: &app-name emqx-operator-ca
spec:
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: emqx-operator-self-signed
  commonName: *app-name
  subject:
    countries:
      - "UNC"
    provinces:
      - "UNC"
    localities:
      - "UNC"
    organizations:
      - *app-namespace
    organizationalUnits:
      - "KubeStation:aiot@aiot.hk"
  isCA: true
  usages:
    - digital signature
    - key encipherment
    - cert sign
    - crl sign
  encodeUsagesInRequest: true
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS1
    rotationPolicy: Always
  duration: {{kube.cert.signingDuration}}
  renewBefore: 360h    # 15d
  secretName: *app-name

---
kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: &app-name emqx-operator
spec:
  ca:
    secretName: emqx-operator-ca
    crlDistributionPoints:
      - "https://aiot.hk"
