---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  namespace: &app-namespace aiot-case
  name: &app-name mqtt-edge-nanomq
spec:
  issuerRef:
    kind: Issuer
    group: cert-manager.io
    name: mqtt-edge-nanomq
  commonName: *app-name
  subject:
    countries:
      - "UNC"
    provinces:
      - "UNC"
    localities:
      - "UNC"
    organizations:
      - *app-namespace
    organizationalUnits:
      - "KubeStation:aiot@aiot.hk"
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  encodeUsagesInRequest: true
  dnsNames:
    - localhost
    - mqtt-edge-nanomq
    - mqtt-edge-nanomq.aiot-case
    - mqtt-edge-nanomq.aiot-case.svc
    - mqtt-edge-nanomq.aiot-case.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS1
    rotationPolicy: Always
  duration: {{kube.cert.signingDuration}}
  renewBefore: 360h    # 15d
  secretName: mqtt-edge-nanomq-cert


---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  namespace: &app-namespace aiot-case
  name: &app-name mqtt-edge-nanomq-client-mqttx
spec:
  issuerRef:
    kind: Issuer
    group: cert-manager.io
    name: mqtt-edge-nanomq
  commonName: *app-name
  subject:
    countries:
      - "UNC"
    provinces:
      - "UNC"
    localities:
      - "UNC"
    organizations:
      - *app-namespace
    organizationalUnits:
      - "KubeStation:aiot@aiot.hk"
  usages:
    - digital signature
    - key encipherment
    - client auth
  encodeUsagesInRequest: true
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS1
    rotationPolicy: Always
  duration: {{kube.cert.signingDuration}}
  renewBefore: 360h    # 15d
  secretName: mqtt-edge-nanomq-client-mqttx-cert
