---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  namespace: &app-namespace aiot-case
  name: &app-name nanomq
spec:
  issuerRef:
    kind: Issuer
    group: cert-manager.io
    name: nanomq
  commonName: *app-name
  subject:
    countries:
      - "UNC"
    provinces:
      - "UNC"
    localities:
      - "UNC"
    organizations:
      - *app-namespace
    organizationalUnits:
      - "KubeStation:aiot@aiot.hk"
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  encodeUsagesInRequest: true
  dnsNames:
    - localhost
    - nanomq
    - nanomq.aiot-case
    - nanomq.aiot-case.svc
    - nanomq.aiot-case.svc.cluster.local
    - "*.nanomq"
    - "*.nanomq.aiot-case"
    - "*.nanomq.aiot-case.svc"
    - "*.nanomq.aiot-case.svc.cluster.local"
  ipAddresses:
    # todo: should contain the node-ip of each nanomq instance
    - 127.0.0.1
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS1
    rotationPolicy: Always
  duration: {{kube.cert.signingDuration}}
  renewBefore: 360h    # 15d
  secretName: nanomq-cert


---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  namespace: &app-namespace aiot-case
  name: &app-name nanomq-client-mqttx
spec:
  issuerRef:
    kind: Issuer
    group: cert-manager.io
    name: nanomq
  commonName: *app-name
  subject:
    countries:
      - "UNC"
    provinces:
      - "UNC"
    localities:
      - "UNC"
    organizations:
      - *app-namespace
    organizationalUnits:
      - "KubeStation:aiot@aiot.hk"
  usages:
    - digital signature
    - key encipherment
    - client auth
  encodeUsagesInRequest: true
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS1
    rotationPolicy: Always
  duration: {{kube.cert.signingDuration}}
  renewBefore: 360h    # 15d
  secretName: nanomq-client-cert-mqttx
