---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: &app-namespace aiot-case
  name: &app-name mqtt-edge-nanomq
  # annotations:
  #   kubereloader.kubestation.aiot.hk/auto: "true"
spec:
  selector:
    matchLabels: &app-label
      app.kubernetes.io/name: mqtt-edge-nanomq
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: *app-namespace
      app.kubernetes.io/managed-by: kube
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 75%
  revisionHistoryLimit: 5

  template:
    metadata:
      labels:
        <<: *app-label

    spec:
      serviceAccountName: default
      automountServiceAccountToken: false

      terminationGracePeriodSeconds: 0
      nodeSelector:
        node-role.kubernetes.io/edge: ""
        node-role.kubernetes.io/aiot-case: ""
      tolerations:
        - operator: Exists

      hostIPC: false
      hostPID: false
      hostNetwork: true

      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        options:
          - name: single-request-reopen

      restartPolicy: Always

      volumes:
        - name: config
          configMap:
            name: mqtt-edge-nanomq
            defaultMode: 0644
            optional: true

        - name: cert
          secret:
            secretName: mqtt-edge-nanomq-cert
            defaultMode: 0644
            optional: true

      containers:
        - image: {{kubestore.image.repository}}/nanomq:{{kubethings.aiot.edge.nanomq.app.version}}
          imagePullPolicy: {{kubestore.image.pullPolicy}}
          name: *app-name

          volumeMounts:
            - name: config
              mountPath: /etc/nanomq/config/
              readOnly: false

            - name: cert
              mountPath: /etc/nanomq/pki/
              readOnly: true

          # envFrom:
          #   - configMapRef:
          #       name: mqtt-edge-nanomq-env
          #       optional: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          securityContext:
            runAsGroup: 0
            runAsUser: 0
            runAsNonRoot: false
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

          stdin: false
          tty: false
          terminationMessagePolicy: FallbackToLogsOnError
          terminationMessagePath: /dev/termination-log
          command:
            - /usr/local/bin/nanomq

          ports:
            - name: admission
              protocol: TCP
              containerPort: 9443
            - name: metric
              protocol: TCP
              containerPort: &port-metric 80
          # startupProbe:
          #   tcpSocket:
          #     port: *port-metric
          #   initialDelaySeconds: 0
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   successThreshold: 1
          #   failureThreshold: 24
          # readinessProbe:
          #   tcpSocket:
          #     port: *port-metric
          #   initialDelaySeconds: 0
          #   periodSeconds: 5
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   failureThreshold: 1
          # livenessProbe:
          #   tcpSocket:
          #     port: *port-metric
          #   initialDelaySeconds: 0
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   successThreshold: 1
          #   failureThreshold: 2
